apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: giggleusa-org-tls
spec:
  secretName: giggleusa-org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: giggleusa.org
  dnsNames:
    - giggleusa.org
    - www.giggleusa.org
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - giggleusa.org
          - www.giggleusa.org